en-US: 
  institutionName:  '{regionLabel} House Assisted Living'  
  formHeader:  'Please fill out the form'
  procedureA:  'Was procedure A performed?'
  procedureB:  'Was procedure B performed?'
  procedureC:  'Was procedure C performed?'
  yes:  'Yes'
  no:  'No'
es-US:
  institutionName:  'Casa del {regionLabel} vida asistida'  
  formHeader:  'Por favor rellene el formulario'
  procedureA:  '¿Se realizó el procedimiento A?'
  procedureB:  '¿Se realizó el procedimiento B?'
  procedureC:  '¿Se realizó el procedimiento C?'
  yes:  'Sí'
  no:  'No'
