en-US: 
  institutionName:  '{regionLabel}'  
  formHeader:  'Please fill out the form'
  optionA:  'Was option A performed?'
  optionB:  'Was option B performed?'
  optionC:  'Was option C performed?'
  yes:  'Yes'
  no:  'No'
  submit:  'Submit'
es-US:
  institutionName:  '{regionLabel}'  
  formHeader:  'Por favor rellene el formulario'
  optionA:  '¿Se realizó el option A?'
  optionB:  '¿Se realizó el option B?'
  optionC:  '¿Se realizó el option C?'
  yes:  'Sí'
  no:  'No'
  submit: 'Presentar'
